name: "Flujo CI-Build"
run-name: "CI-Build para ${{ github.event_name }} de ${{ github.actor }} en ${{ github.ref }}"

on:
  pull_request:
    branches: ["main"]
    types: [closed]

env:
  ANGULAR_CLI_VERSION: 19

jobs:
  linter:
    runs-on: self-hosted
    container:
      image: node:20
      options: --volume /home/desarrollo2/build_output:/workspace

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Instalar CLI de Angular"
        run: npm install -g @angular/cli@${{ env.ANGULAR_CLI_VERSION }}

      - name: "Instalar dependencias"
        run: npm install

      - name: "Ejecutar linter"
        run: npm run lint

  build:
    needs: linter
    runs-on: self-hosted
    container:
      image: node:20
      options: --volume /home/desarrollo2/iu:/workspace

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Instalar CLI de Angular"
        run: npm install -g @angular/cli@${{ env.ANGULAR_CLI_VERSION }}

      - name: "Instalar dependencias"
        run: npm install

      - name: "Compilar Angular"
        run: ng build --configuration=production --output-path=/workspace/

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: "Verificar archivos en volumen compartido"
        run: ls -l /home/desarrollo2/build_output/
      - name: "Crear carpeta destino si no existe"
        run: mkdir -p /home/desarrollo2/iu/IU_Indicadores/dist/

      # - name: "Mover archivos al destino final"
      #   run: sudo mv /home/desarrollo2/build_output/iu_indicadores /home/desarrollo2/iu/IU_Indicadores/dist/

      # - name: "Verificar archivos en la nueva ubicación"
      #   run: ls -l /home/desarrollo2/iu/IU_Indicadores/dist/

      # - name: "Reiniciar Nginx después del despliegue"
      #   run:  systemctl restart nginx
