# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Triggers
run-name: Estoy Usando triggers!
on:
  pull_request:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: "lenguaje favorito"
        required: true
        default: "Mundo"
        type: choice
        options:
          - Mundo
          - Python
          - JavaScript
      nombre:
        description: "Tu nombre"
        required: true
        default: "Juan"
        type: string

  schedule:
    - cron: "15 22 * * *" # Cada día a la medianoche UTC

jobs:
  hola-mundo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Correr commando
        run: echo USERNAME=${{inputs.nombre}} LENGUAJE=${{inputs.lenguaje_favorito}} >> GITHUB_ENV
